INSERT INTO CLIENT (ID, FIRST_NAME, LAST_NAME) VALUES (1, '1', '1');
INSERT INTO CLIENT (ID, FIRST_NAME, LAST_NAME) VALUES (2, '2', '2');
INSERT INTO CLIENT (ID, FIRST_NAME, LAST_NAME) VALUES (3, '3', '3');
INSERT INTO CLIENT (ID, FIRST_NAME, LAST_NAME) VALUES (4, '4', '4');
INSERT INTO CLIENT (ID, FIRST_NAME, LAST_NAME) VALUES (5, '5', '5');